development:
  adapter: postgresql
  encoding: unicode
  database: deviseapi
  host: localhost
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: deviseapitest
  pool: 5
  username: postgres
  password: postgres
